eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)

main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home),
    path('about/', views.about),
    path('calculator/', views.calculator),
    path('phone-detail/<int:phone_id>/' , views.phone_detail),
    path('get-person/<int:person_id>/' , views.person_detail),
    path('get-person-products/<int:person_id>/' , views.get_person_products)
]


def clown():
    print(clown)

users/urls.py
from django.urls import path, include
from . import views
from . import cabinet_views as cabinet

urlpatterns = [
    path('cabinet/', cabinet.settings),
    path('my-products/', cabinet.products),
]

phones_urls = [
    path('cabinet/add-phone/', cabinet.add_phone),
    path('cabinet/delete-phone/<int:phone_id>', cabinet.delete_phone)
]

auth_urls = [
    path('login/', views.login_view),  # /users/login/
    path('register/', views.register_view),  # /users/register/
    path('logout/', views.logout_view),  # /users/logout/
]

urlpatterns += auth_urls
urlpatterns += phones_urls

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
MAX_RATE = 5


class Person(models.Model):
    STATUS_CHOICES = (
        ('golden', 'Золотой продавец'),
        ('silver', 'Серебрянный продавец'),
        ('simple', 'Продавец'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    date_birth = models.DateField(blank=True, null=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=20)
    rate = models.FloatField(default=4, blank=True, null=True)
    count_sold_products = models.IntegerField(default=0)
    online = models.BooleanField(default=False)

    # TODO: add type of products

    def __str__(self):
        return '{} {} {}'.format(self.user.first_name, self.user.last_name, self.user.email)

    def get_name(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

    def get_rate(self):
        return (self.rate / MAX_RATE) * 100

    def get_phones(self):
        return Phone.objects.filter(person=self)


class Phone(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE, default=1, null=True, blank=True)
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    price = models.FloatField(default=100)
    is_sale = models.BooleanField(default=False)
    percent_sale = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return '{} {} {}$'.format(self.name, self.brand, self.price)

    def get_price(self):
        if self.is_sale:
            return self.price * (1 - self.percent_sale / 100)
        else:
            return self.price

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from main.models import Person, Phone


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=255, required=False)
    second_name = forms.CharField(max_length=255, required=False)
    email = forms.EmailField(max_length=255, required=False)

    def save(self, *args, **kwargs):
        data = self.cleaned_data
        django_profile = User.objects.create_user(
            username=data['username'],
            password=data['password2'],
            first_name=data['first_name'],
            last_name=data['second_name'],
            email=data['email']
        )
        Person.objects.create(user=django_profile)
        return django_profile


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['phone_number', 'date_birth']


class PhoneForm(forms.ModelForm):
    class Meta:
        model = Phone
        # fields = '__all__'
        exclude = ['person']

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Phone, Person


# Create your views here.


def home(request):
    all_phones = Phone.objects.all()
    total_sum = 0
    for phone in all_phones:
        total_sum += phone.get_price()
    return render(request, 'home.html', {
        'total_sum': total_sum,
        'all_phones': all_phones,
        'tab': 'home'
    })


def about(request):
    return render(request, 'about.html', {
        'a': 5 + 5,
        'list': [1, 2, 3, 4, 5],
        'tab': 'about'
    })


def phone_detail(request, phone_id):
    phone = Phone.objects.get(id=phone_id)
    print('phone_id  = ', phone)
    return render(request, 'phone_detail.html', {
        "phone": phone
    })


calc_map = {
    '+': lambda x, y: x + y,
    '-': lambda x, y: x - y,
    '*': lambda x, y: x * y,
    '/': lambda x, y: x / y,
}


def calculator(request):
    ctx = {
        'tab': 'calc',
        'digits': [i for i in range(10)]
    }
    if request.method == 'POST':
        try:
            first_number = float(request.POST.get('first_number'))  # ['first_number']
            operation = request.POST.get('operation')
            second_number = float(request.POST.get('second_number'))
            ctx['result'] = calc_map[operation](first_number, second_number)
        except Exception as e:
            ctx['error'] = str(e)
    return render(request, 'calculator.html', ctx)


def person_detail(request, person_id):
    ctx = {}
    ctx['person'] = Person.objects.get(id=person_id)
    return render(request, 'person/index.html', ctx)


def get_person_products(request, person_id):
    ctx = {}
    phones = Person.objects.get(id=person_id).get_phones()
    total_sum = sum([ph.get_price() for ph in phones])
    ctx['phones'] = phones
    ctx['person_id'] = person_id
    ctx['total_sum'] = total_sum
    return render(request, 'person/products.html', ctx)
def f():
    print('Hello world')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm
from django.contrib.auth import authenticate, login, logout


# Create your views here.


def login_view(request):
    ctx = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        auth_user = authenticate(username=username, password=password)
        if auth_user:
            login(request, auth_user)
            return redirect('/')
        else:
            ctx['error'] = 'User not found!'
        print(username, password)
    return render(request, 'users/login.html', ctx)


def register_view(request):
    context = {
        'form': RegisterForm()
    }

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = user.username
            password = form.cleaned_data['password1']
            print('django_password', user.password)
            print('valid form!', username, password)
            auth_user = authenticate(username=username, password=password)
            if auth_user:
                login(request, auth_user)
                return redirect('/')
        else:
            context['form'] = form
    return render(request, 'users/register.html', context)


def logout_view(request):
    logout(request)
    return redirect('/')

main/templates/about.html
{% extends 'index.html' %}
{% block content %}
<a href="https://google.com" target="_blank"> Go to google!</a>
<br>
text <input type="text">
<br>
number <input type="number">

<br>
search <input type="search">
<br>
range <input type="range" min="0" max="100" step="1">
<br>
color <input type="color">
<br>
checkbox <input type="checkbox">


<br>
radio
1<input type="radio" name="radio_btn">
2<input type="radio" name="radio_btn">
3<input type="radio" name="radio_btn">
4<input type="radio" name="radio_btn">

<br>
select

<select name="" id="">
    <option value="">Lorem ipsum.</option>
    <option value="">2.</option>
    <option value="">3.</option>
    <option value="">4.</option>
</select>
<br>
select multiple

<select name="" id="" multiple>
    <option value="">Lorem ipsum.</option>
    <option value="">2.</option>
    <option value="">3.</option>
    <option value="">4.</option>
</select>
<br>
textarea
<textarea name="" id="" cols="30" rows="10"></textarea>


<div>
    Lorem ipsum dolor sit amet, consectetur.
</div>

<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolore dolorem ea esse necessitatibus pariatur tempora
    totam velit voluptatibus. Amet, reiciendis!
</div>
{% endblock %}

main/templates/calculator.html
{% extends 'index.html' %}
{% block content %}
<h1>Calc page!</h1>

<form action="" method="post">
    {% csrf_token %}
    <input type="number" name="first_number">
    <select name="operation" id="">
        <option value="+">add</option>
        <option value="-">sub</option>
        <option value="*">mul</option>
        <option value="/">div</option>
    </select>
    <input type="number" name="second_number">
    <button class="btn btn-danger">Calculate</button>
    {% if result %} = {{result}} {% endif %}
</form>

{% if error %}
<p class="alert alert-danger">{{error}}</p>

{% endif %}

<div class="col-md-4">
    <div class="row">
        {% for num in digits %}
            <div class="col-md-3 btn-primary" style="margin-bottom: 2px; margin: 1px">{{ num }}</div>
        {% endfor %}
         <div class="col-md-3 btn-info">=</div>
         <div class="col-md-3 btn-danger">Clear</div>
    </div>
</div>


<form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" name="check_me_out" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

main/templates/home.html
{% extends 'index.html' %}


{% block content %}
<h1>Phones: {{ all_phones | length }}. Total sum : {{total_sum}}$</h1>

<div class="container">
    <table class="table table-striped table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Brand</th>
            <th scope="col">Person</th>
        </tr>
        </thead>
        <tbody>
        {% for phone in all_phones %}
        <tr>
            <td scope="row">{{phone.id}}</td>
            <td><a href="/phone-detail/{{phone.id}}">{{phone.name}}
                {% if phone.is_sale %} <span class="badge badge-secondary">Sale</span> {% endif %}
            </a></td>
            <td>{{ phone.price }}
                {% if phone.is_sale %} - {{ phone.percent_sale }} % = {{ phone.get_price }} {% endif %} $
            </td>
            <td>{{ phone.brand }}</td>

            <td><a href="/get-person/{{phone.person.id}}">{{ phone.person.get_name }}</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

main/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>

{% include 'partials/header.html' %}

<div class="container">
    {% block content %}


    {% endblock content %}
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

main/templates/partials/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: rgb(248, 119, 119)!important;">
  <a class="navbar-brand" href="/">E.SHOP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if tab == 'home' %} active {% endif %}">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if tab == 'about' %} active {% endif %}">
        <a class="nav-link" href="/about/">About</a>
      </li>
      <li class="nav-item {% if tab == 'calc' %} active {% endif %}">
        <a class="nav-link" href="/calculator/">Calculator</a>
      </li>
    </ul>
    <span class="navbar-text">

      {% if request.user.is_authenticated  %}
        <a class="btn btn-danger" href="/users/logout/">Logout ({{ request.user }}) </a>
        <a class="btn btn-info" href="/users/cabinet/">Cabinet</a>
      {% else %}
        <a class="btn btn-success" href="/users/login/">Login</a>
        <a class="btn btn-primary" href="/users/register/">Register</a>
      {% endif %}
        <a class="btn btn-warning" href="">Wish list</a>
    </span>
  </div>
</nav>

main/templates/person/index.html
{% extends 'index.html' %}


{% block content %}
<h1>Person Detail</h1>
<p>Name : {{ person.first_name }}</p>
<p>Last Name : {{ person.last_name }}</p>
<p>email : {{ person.email }}</p>
<p>phone_number : {{ person.phone_number }}</p>
<p>status : {{ person.get_status_display }}</p>
<p>
<div class="row">
    <div class="col-md-2">
        rate : {{person.rate}} / 5
    </div>
    <div class="col-md-5">
        <div class="progress">
            <div class="progress-bar progress-bar-striped bg-warning" role="progressbar"
                 style="width: {{ person.get_rate }}%"
                 aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">{{ person.get_rate }} %
            </div>
        </div>
    </div>
</div>


</p>
<p>count sold products : {{ person.count_sold_products }}</p>
<p>
    {% if person.online %}
    <span style="color: green;">Online</span>
    {% else %}
    <span style="color: darkred;">Offline</span>

    {% endif %}
</p>

<a class="btn btn-success" href="/get-person-products/{{person.id}}/">Go to phones >>> </a>


{% endblock content %}

main/templates/person/products.html
{% extends 'index.html' %}


{% block content %}
<a class="btn btn-primary" href="/get-person/{{person_id}}">Back</a>
<br>
Total - {{total_sum}} $
<table class="table table-striped table-dark">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">Brand</th>
    </tr>
    </thead>
    <tbody>
    {% for phone in phones %}
    <tr>
        <td scope="row">{{phone.id}}</td>
        <td><a href="/phone-detail/{{phone.id}}">{{phone.name}}
            {% if phone.is_sale %} <span class="badge badge-secondary">Sale</span> {% endif %}
        </a></td>
        <td>{{ phone.price }}
            {% if phone.is_sale %} - {{ phone.percent_sale }} % = {{ phone.get_price }} {% endif %} $
        </td>
        <td>{{ phone.brand }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock content %}

main/templates/phone_detail.html
{% extends 'index.html' %}
{% block content %}
<h1>Phone detail! (Person  -


    <a href="/get-person/{{phone.person.id}}">{{ phone.person.get_name }}</a>)</h1>
<h2><a href="/get-person-products/{{phone.person.id}}">Все товары продавца</a> </h2>
<h3>{{ phone.name }}</h3>
<p>Brand: {{ phone.brand }}</p>
<p>Description: {{ phone.description }}</p>
<p>Price:
{% if phone.is_sale %}
<span style="color:red;">{{ phone.price }} $  <b>-</b> {{ phone.percent_sale }}% </span>
<span style="color: green;"> {{ phone.get_price }} $</span>
    {% else %}
    <span>{{phone.price}} $</span>
{% endif %}
</p>
<a class="btn btn-success" href="">Add to bucket</a>
<a class="btn btn-warning" href="">Add to wish list</a>
{% endblock %}

main/templates/users/cabinet/main.html
{% extends 'index.html' %}

{% block content %}
<h1>Hello {{ request.user.first_name }} {{request.user.last_name}}!</h1>

<div class="row">
    <div class="col-md-3">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link {% if tab == 'settings' %}active{% endif %} " href="/users/cabinet/">Settings</a>
            <a class="nav-link {% if tab == 'products' %}active{% endif %} " href="/users/my-products/">My products</a>
            <a class="nav-link {% if tab == 'messages' %}active{% endif %} " href="">Messages</a>
            <a class="nav-link {% if tab == 'statictics' %}active{% endif %} ">Statictics</a>
        </div>
    </div>

    {% load crispy_forms_tags %}
    <div class="col-md-9">
        {% block cabinet %}
        <form action="/users/cabinet/" method="post">
            {% csrf_token %}
            <div>
                <label for="">First Name</label>
                <input type="text" value="{{request.user.first_name}}" name="first_name">
            </div>
            <div>
                <label for="">Last Name</label>
                <input type="text" value="{{request.user.last_name}}" name="last_name">
            </div>
            <div>
                <label for="">Email</label>
                <input type="text" value="{{request.user.email}}" name="email">

            </div>
            {{ form|crispy }}
            <button class="btn btn-success">Save</button>
        </form>
        {% endblock %}
    </div>
</div>


{% endblock %}

main/templates/users/cabinet/products.html
{% extends 'users/cabinet/main.html' %}

{% block cabinet %}
<h1>My products</h1>
<div>
    <a class="btn btn-success" href="/users/cabinet/add-phone/">Add phone</a>
</div>

<table class="table table-striped table-dark">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Brand</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        {% for phone in all_products %}
        <tr>
            <td scope="row">{{phone.id}}</td>
            <td>
                <a href="/phone-detail/{{phone.id}}">{{phone.name}}
                {% if phone.is_sale %} <span class="badge badge-secondary">Sale</span> {% endif %}
            </a></td>
            <td>{{ phone.price }}
                {% if phone.is_sale %} - {{ phone.percent_sale }} % = {{ phone.get_price }} {% endif %} $
            </td>
            <td>{{ phone.brand }}</td>

            <td>
                <a class="btn btn-danger" href="/users/cabinet/delete-phone/{{ phone.id }}">X</a>
                <a class="btn btn-warning" href="">update</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock cabinet %}

main/templates/users/login.html
{% extends 'index.html' %}

{% block content %}
<h1>Login page!</h1>
<a class="btn btn-primary" href="/users/register/">Register</a>

<form action="." method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleInputEmail1">Username</label>
        <input type="text"
               class="form-control"
               id="exampleInputEmail1"
               aria-describedby="emailHelp"
               name="username"
               placeholder="Enter username">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password"
               class="form-control"
               id="exampleInputPassword1"
               name="password"
               placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% if error %}
<p class="alert alert-danger">{{error}}</p>
{% endif %}
{% endblock content %}

main/templates/users/products/phone.html
{% extends 'users/cabinet/main.html' %}

{% block cabinet %}
<h1>Add phone</h1>

{% if result %}
<p class="alert alert-success">Success!</p>

{% endif %}
{% load crispy_forms_tags %}
<div>
    <a class="btn btn-link" href="/users/my-products/"> <<< back to all products</a>
    <form action="/users/cabinet/add-phone/" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock cabinet %}

main/templates/users/register.html
{% extends 'index.html' %}

{% block content %}
<h1>Register <a class="btn btn-dark" href="/users/login">Login</a></h1>

{% load crispy_forms_tags %}
<form action="/users/register/" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div>
        {{field|as_crispy_field}}
        {% if field.errors %}
        <ul>
        {% for err in field.errors %}
            <li style="color: red;">{{ err }}</li>
        {% endfor %}
            </ul>
        {% endif %}
    </div>
    {% endfor %}

    <button class="btn btn-primary">Save</button>
</form>
{% endblock content %}